import type { Config } from 'tailwindcss'

const config: Config = {
	darkMode: ['class'],
	content: ['./src/**/*.{ts,tsx}'],
	theme: {
		extend: {
			colors: {
				brand: {
					50: '#F0FDF4',
					100: '#DCFCE7',
					200: '#BBF7D0',
					500: '#22C55E',
					600: '#16A34A',
					700: '#15803D',
					800: '#166534',
					900: '#14532D',
				},
				page: 'var(--shop-canvas)',
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				shop: {
					canvas: 'var(--shop-canvas)',
					surface: 'var(--shop-surface)',
					'surface-elevated': 'var(--shop-surface-elevated)',
					'surface-subtle': 'var(--shop-surface-subtle)',
					ink: 'var(--shop-ink)',
					'ink-muted': 'var(--shop-ink-muted)',
					'ink-faint': 'var(--shop-ink-faint)',
					border: 'var(--shop-border)',
					'border-strong': 'var(--shop-border-strong)',
					primary: 'var(--shop-primary)',
					'primary-strong': 'var(--shop-primary-strong)',
					'primary-hover': 'var(--shop-primary-hover)',
					'primary-soft': 'var(--shop-primary-soft)',
					action: 'var(--shop-action)',
					'action-hover': 'var(--shop-action-hover)',
					'action-soft': 'var(--shop-action-soft)',
					trust: 'var(--shop-trust)',
					'trust-soft': 'var(--shop-trust-soft)',
					accent: 'var(--shop-accent)',
					success: 'var(--shop-success)',
					warning: 'var(--shop-warning)',
					danger: 'var(--shop-danger)',
					discount: 'var(--shop-discount)',
					'free-delivery': 'var(--shop-free-delivery)',
				},
			},
			fontFamily: {
				sans: ['var(--font-plus-jakarta)', 'DM Sans', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
				shop4: 'var(--shop-radius-4)',
				shop8: 'var(--shop-radius-8)',
				shop12: 'var(--shop-radius-12)',
				shop16: 'var(--shop-radius-16)',
				shop22: 'var(--shop-radius-22)',
				shop28: 'var(--shop-radius-28)',
				shop32: 'var(--shop-radius-32)',
				shopPill: 'var(--shop-radius-pill)',
			},
			backgroundImage: {
				'shop-page': 'var(--shop-page-gradient)',
				'shop-hero': 'var(--shop-hero-surface)',
				'shop-promo': 'var(--shop-promo-surface)',
				'shop-footer': 'var(--shop-footer-surface)',
			},
			boxShadow: {
				shop1: 'var(--shop-shadow-level-1)',
				shop2: 'var(--shop-shadow-level-2)',
				shop3: 'var(--shop-shadow-level-3)',
				shop4: 'var(--shop-shadow-level-4)',
				shopSoft: 'var(--shop-shadow-soft)',
				shopStrong: 'var(--shop-shadow-strong)',
				'warm-sm': 'var(--shop-shadow-level-1)',
				'warm-md': 'var(--shop-shadow-level-2)',
				'warm-lg': 'var(--shop-shadow-level-5)',
				glow: 'var(--shop-shadow-glow-purple)',
				'shop-1': '0 2px 8px rgba(26,35,43,0.06), 0 1px 3px rgba(26,35,43,0.04)',
				'shop-2': '0 4px 16px rgba(26,35,43,0.08), 0 2px 6px rgba(26,35,43,0.05)',
				'shop-3': '0 8px 32px rgba(110,73,216,0.12), 0 2px 8px rgba(110,73,216,0.06)',
				'shop-4': '0 1px 0 rgba(26,35,43,0.06), 0 4px 20px rgba(26,35,43,0.10)',
				'shop-5': '0 12px 40px rgba(26,35,43,0.12), 0 4px 12px rgba(26,35,43,0.08)',
				'nav-up': '0 -8px 32px rgba(26,35,43,0.08), 0 -1px 0 rgba(26,35,43,0.06)',
				'green-glow': 'var(--shop-shadow-glow-green)',
				'green-glow-hover': 'var(--shop-shadow-glow-green-hover)',
				'purple-glow': 'var(--shop-shadow-glow-purple)',
			},
			transitionDuration: {
				'80': '80ms',
				'220': '220ms',
				'250': '250ms',
				'320': '320ms',
				'380': '380ms',
				'400': '400ms',
				'600': '600ms',
			},
			padding: {
				'safe-bottom': 'env(safe-area-inset-bottom)',
				'safe-top': 'env(safe-area-inset-top)',
			},
			animation: {
				'slide-up': 'slideUp 0.3s ease-out',
				'slide-down': 'slideDown 0.3s ease-out',
				'fade-in': 'fadeIn 0.2s ease-out',
				shimmer: 'warmShimmer 1.5s linear infinite',
				'badge-bounce': 'badgeBounce 0.3s ease-out',
				marquee: 'marquee var(--duration) infinite linear',
				'marquee-vertical': 'marquee-vertical var(--duration) linear infinite',
			},
			keyframes: {
				slideUp: {
					from: { opacity: '0', transform: 'translateY(12px)' },
					to: { opacity: '1', transform: 'translateY(0)' },
				},
				slideDown: {
					from: { opacity: '0', transform: 'translateY(-8px)' },
					to: { opacity: '1', transform: 'translateY(0)' },
				},
				fadeIn: {
					from: { opacity: '0' },
					to: { opacity: '1' },
				},
				warmShimmer: {
					'0%': { backgroundPosition: '200% 0' },
					'100%': { backgroundPosition: '-200% 0' },
				},
				badgeBounce: {
					'0%': { transform: 'scale(1)' },
					'50%': { transform: 'scale(1.3)' },
					'100%': { transform: 'scale(1)' },
				},
				marquee: {
					from: { transform: 'translateX(0)' },
					to: { transform: 'translateX(calc(-100% - var(--gap)))' },
				},
				'marquee-vertical': {
					from: { transform: 'translateY(0)' },
					to: { transform: 'translateY(calc(-100% - var(--gap)))' },
				},
			},
		},
	},
	plugins: [
		require('tailwindcss-animate'),
		require('@tailwindcss/typography'),
	],
}

export default config
